sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_0456f39a3ae3_key -iv $encrypted_0456f39a3ae3_iv -in complex-k8s.json.enc -out complex-k8s.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file complex-k8s.json
  - gcloud config set project complex-k8s-309722
  - gcloud config set compute/zone us-central1-c
  - glcoud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t froliceric/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true froliceric/react-test npm test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: main
